name: 'Setup Minecraft'
description: 'Setup a Minecraft server'
inputs:
  version:
    description: 'Minecraft version to use'
    required: false
    default: 'snapshot'
  skippedVersion:
    description: 'Minecraft version to be skipped'
    required: false
outputs:
  version:
    description: 'Minecraft version used'
runs:
  using: 'node12'
  main: 'dist/index.js'
