name: update

on:
  push:
    branches:
      - "main"
    paths:
      - "index.js"
      - "package.json"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: npm run package
      - run: |
          git config --global user.name "mcenv"
          git config --global user.email "mcenv@users.noreply.github.com"
          git add --force dist/index.js dist/licenses.txt
          git switch dist
          git restore --source=main --staged -- action.yml LICENSE README.md dist/index.js dist/licenses.txt
          git add .
          git commit --message "Update"
          git push
